apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatekey-postgresql-data
  labels:
    app.kubernetes.io/name: gatekey
    app.kubernetes.io/component: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
